name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Firebase credentials
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json
        
    - name: Setup test user
      run: npm run setup-test-user
      
    - name: Start development server
      run: |
        npm run dev &
        sleep 10
        
    - name: Wait for server
      run: |
        npx wait-on http://localhost:5173/project-01-bookmemo || npx wait-on https://localhost:5173/project-01-bookmemo
      
    - name: Run E2E tests
      run: npx cypress run
      
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        
    - name: Upload videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos 